### ISSUE TITLE
Printing String not terminated

### ISSUE THREAD

**Issue by showierdata9978** [RJmsG/ACPL#2]
![image](https://user-images.githubusercontent.com/68120127/208331495-3df06841-71cb-426f-a2db-2e1ca022edf5.png)

**Comment by RJmsG** [comment]
It works fine when I use it. Seems like you forgot to add a newline at the end of your source code.

**Comment by RJmsG** [comment]
I just fixed test.acpl, but it still says "1 lines". Hopefully people who use it dont run into any problems.

**Comment by showierdata9978** [comment]
check if a newline is at the end of a file; if not raise an error

**Comment by RJmsG** [comment]
> 

alright. that will be added in the next update. You can mess with it in the other branch
