### ISSUE TITLE
please rewrite using more then 1 compiling function, and use generators, and dont use global vars

### ISSUE THREAD

**Issue by showierdata9978** [RJmsG/ACPL#5]

**Comment by RJmsG** [comment]
Yes, I plan on removing global vars. I'll try thinking of other compile functions

**Comment by showierdata9978** [comment]
by compile functions, i mean split the main compiling function to more then 1 function

https://www.quora.com/Is-it-better-to-write-several-smaller-functions-or-one-larger-function-to-perform-certain-task

**Comment by RJmsG** [comment]
Oh okay

**Comment by RJmsG** [comment]
Any small functions will end up getting larger anyway
